# Generated by Django 6.0.1 on 2026-01-10 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(
                    choices=[
                        ('created', 'Created'),
                        ('in_transit', 'In Transit'),
                        ('out_for_delivery', 'Out for Delivery'),
                        ('delivered', 'Delivered')
                    ],
                    default='created',
                    max_length=32
                )),
                ('origin', models.CharField(blank=True, max_length=255)),
                ('destination', models.CharField(blank=True, max_length=255)),

                # Added fields for route visualization
                ('origin_lat', models.FloatField(blank=True, null=True)),
                ('origin_lng', models.FloatField(blank=True, null=True)),
                ('dest_lat', models.FloatField(blank=True, null=True)),
                ('dest_lng', models.FloatField(blank=True, null=True)),

                # Current location
                ('current_lat', models.FloatField(blank=True, null=True)),
                ('current_lng', models.FloatField(blank=True, null=True)),

                # ETA for delivery
                ('estimated_delivery', models.DateTimeField(blank=True, null=True)),

                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),

                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tracking.shipment')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]